apiVersion: v1
kind: Service
metadata:
  name: example-api-service
spec:
  type: ClusterIP
  selector:
    app: example-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    name: http-port