apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-api
spec:
  selector:
    matchLabels:
      app: example-api
  template:
    metadata:
      labels:
        app: example-api
    spec:
      containers:
      - name: example-echo-api
        image: curity/simple-echo-api:1.0
        env:
        - name: ISSUER
          value: "https://login.example.eks/~"
        ports:
        - containerPort: 3000
